version: '3'
services:
#   app:
#     restart: always
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - 8000:8000
  db:
    image: mysql:latest
    container_name: laravel-db
    command: mysqld --default-authentication-plugin=mysql_native_password --innodb_use_native_aio=0
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    ports:
        - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
